// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_DQgAX46tjnWJFa4_RHVwL3iSw-mZmRc',
    appId: '1:861396158838:web:b5436b4821a55533b11257',
    messagingSenderId: '861396158838',
    projectId: 'mtaa-2d73f',
    authDomain: 'mtaa-2d73f.firebaseapp.com',
    storageBucket: 'mtaa-2d73f.firebasestorage.app',
    measurementId: 'G-B3D9THD3FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFSm1HQS9F35SKF1Gyxts5n9Isl1FOAQ',
    appId: '1:861396158838:android:a10c2d7cb89ecc80b11257',
    messagingSenderId: '861396158838',
    projectId: 'mtaa-2d73f',
    storageBucket: 'mtaa-2d73f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Dybkl946EOZH3Pl3bTHFbVBjWI9fh6Y',
    appId: '1:861396158838:ios:ab42f7af620f6e04b11257',
    messagingSenderId: '861396158838',
    projectId: 'mtaa-2d73f',
    storageBucket: 'mtaa-2d73f.firebasestorage.app',
    iosBundleId: 'com.example.mtaaFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Dybkl946EOZH3Pl3bTHFbVBjWI9fh6Y',
    appId: '1:861396158838:ios:ab42f7af620f6e04b11257',
    messagingSenderId: '861396158838',
    projectId: 'mtaa-2d73f',
    storageBucket: 'mtaa-2d73f.firebasestorage.app',
    iosBundleId: 'com.example.mtaaFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_DQgAX46tjnWJFa4_RHVwL3iSw-mZmRc',
    appId: '1:861396158838:web:6effa6a6d2374b51b11257',
    messagingSenderId: '861396158838',
    projectId: 'mtaa-2d73f',
    authDomain: 'mtaa-2d73f.firebaseapp.com',
    storageBucket: 'mtaa-2d73f.firebasestorage.app',
    measurementId: 'G-P5PLNXBQDQ',
  );
}
